'use client';

const CONTACT_EMAIL = process.env.NEXT_PUBLIC_CONTACT_EMAIL ?? 'contact@palpal.app';

export default function PrivacyPage() {
  return (
    <div className="max-w-3xl mx-auto py-8">
      <div className="mb-10">
        <h1 className="heading-primary">Privacy Policy</h1>
        <p className="text-body mt-2">Last updated: {new Date().toLocaleDateString()}</p>
      </div>

      <div className="section-card space-y-8">

        <section>
          <h2 className="section-title">Information I Collect</h2>
          <p className="section-text mb-4">
            palpal is designed with privacy in mind. I collect minimal information necessary to provide the search service:
          </p>
          <ul className="space-y-3 section-text list-disc list-outside ml-5">
            <li><strong style={{ color: 'var(--text-primary)' }}>Saved Content</strong> — Content you choose to save is stored locally in your browser and never sent to my servers.</li>
            <li><strong style={{ color: 'var(--text-primary)' }}>Technical Data</strong> — Basic server logs including IP addresses, timestamps, and error information generated by normal web traffic.</li>
          </ul>
        </section>

        <hr style={{ borderColor: 'rgba(255,255,255,0.07)' }} />

        <section>
          <h2 className="section-title">How I Use This Information</h2>
          <p className="section-text mb-4">The information I collect is used to:</p>
          <ul className="space-y-2 section-text list-disc list-outside ml-5">
            <li>Troubleshoot technical issues</li>
            <li>Maintain the security and integrity of the service</li>
          </ul>
        </section>

        <hr style={{ borderColor: 'rgba(255,255,255,0.07)' }} />

        <section>
          <h2 className="section-title">Local Storage</h2>
          <p className="section-text">
            Your saved content and search preferences are stored locally in your browser using cookies and local storage.
            This data never leaves your device. You can clear it at any time through your browser settings.
          </p>
        </section>

        <hr style={{ borderColor: 'rgba(255,255,255,0.07)' }} />

        <section>
          <h2 className="section-title">Data Sharing</h2>
          <p className="section-text">
            I do not sell, trade, or otherwise transfer your personal information to third parties. This does not include
            trusted third parties who assist in operating this site, such as the hosting provider, so long as those
            parties agree to keep this information confidential.
          </p>
        </section>

        <hr style={{ borderColor: 'rgba(255,255,255,0.07)' }} />

        <section>
          <h2 className="section-title">Podcast Content</h2>
          <p className="section-text">
            palpal indexes podcast content for search purposes. I do not claim ownership of this content.
            All rights remain with the original podcast creators. If you are a content creator and wish to have your
            content removed from the index, please contact me.
          </p>
        </section>

        <hr style={{ borderColor: 'rgba(255,255,255,0.07)' }} />

        <section>
          <h2 className="section-title">Security</h2>
          <p className="section-text">
            I implement appropriate security measures to protect against unauthorized access, alteration, disclosure,
            or destruction of your personal information. However, no method of transmission over the Internet or
            electronic storage is 100% secure.
          </p>
        </section>

        <hr style={{ borderColor: 'rgba(255,255,255,0.07)' }} />

        <section>
          <h2 className="section-title">Changes to This Policy</h2>
          <p className="section-text">
            I may update this Privacy Policy from time to time. Any changes will be posted on this page with an
            updated date at the top.
          </p>
        </section>

        <hr style={{ borderColor: 'rgba(255,255,255,0.07)' }} />

        <section className="text-center pt-2">
          <h2 className="section-title">Contact Me</h2>
          <p className="section-text mb-6">
            If you have any questions about this Privacy Policy or my privacy practices, please get in touch.
          </p>
          <a href={`mailto:${CONTACT_EMAIL}`} className="btn-primary">
            {CONTACT_EMAIL}
          </a>
        </section>

      </div>
    </div>
  );
}
